defaults: &defaults
  some_normal_config: true
  google_client_id: ala_ma_kota
  google_secret: a_kot_ma_ale
  github_client_id: ala_ma_kota
  github_secret: a_kot_ma_ale
development:
  <<: *defaults
test:
  <<: *defaults
staging:
  <<: *defaults
production:
  <<: *defaults
  github_client_id: <%= ENV['GITHUB_CLIENT_ID'] %>
  github_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>
