# Netguru project configuration file
rollbar:
  read_token: '80ea84edbbe043f4a45deec7037f2f56'
  post_server_item_token: '43abef20075143f6832de97b8512eace'
api:
  url: "https://api.netguru.co"
  token: "30c266edccf57ae07d16c53dbbbe5970"
